version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vscode-extension"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 2
    groups:
      npm-monthly-rollup:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 2
    groups:
      cargo-monthly-rollup:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 2
