[mcp]
sse_servers = [ ]
shttp_servers = [ ]

  [[mcp.stdio_servers]]
  name = "time"
  command = "uvx"
  args = [ "mcp-server-time" ]

  [[mcp.stdio_servers]]
  name = "serena"
  command = "uvx"
  args = [
  "--from",
  "git+https://github.com/oraios/serena",
  "serena",
  "start-mcp-server",
  "--context",
  "ide-assistant",
  "--project",
  "./"
]

  [[mcp.stdio_servers]]
  name = "sequential-thinking"
  command = "npx"
  args = [ "-y", "@modelcontextprotocol/server-sequential-thinking" ]
