allow-branch = ["main"]
shared-version = false
dependent-version = "upgrade"
consolidate-commits = true
push = true
push-remote = "origin"
publish = true
tag-name = "v{{version}}"
tag-message = "Release v{{version}}"
rate-limit = 300
pre-release-commit-message = "chore(release): bump version to {{version}} [skip ci]"
sign-commit = false
sign-tag = false
